import { poppins, roboto } from './fonts';
import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from '@components/theme-provider';

export const metadata: Metadata = {
  title: 'Ez Productivity App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} ${poppins.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
